interface IBOOKING_ACTION_TYPES {
  SET_BOOKING_DATA: string;
  DELETE_BOOKING_DATA: string;
}

const BOOKING_ACTION_TYPES: IBOOKING_ACTION_TYPES = {
  SET_BOOKING_DATA: "SET_BOOKING_DATA",
  DELETE_BOOKING_DATA: "DELETE_BOOKING_DATA",
};

export default BOOKING_ACTION_TYPES;
